### ISSUE TITLE
404 not found for a google scholar indexing

### ISSUE THREAD

**Issue by DrilonAvdiu** [acl-org/acl-anthology#574] opened 2019-10-11 17:43 UTC
Hello,

this url "https://www.aclweb.org/anthology/W19-63#page=13" is what google scholar indexed for this search result:

https://scholar.google.com/scholar?cluster=16958290009851606000&hl=en&as_sdt=0,5

May this be a mis-indexing from google's side, or something changed in your repository meanwhile?

Thanks!

**Comment by mjpost** [comment] 2019-10-11 17:48
Duplicate of #569.

**Closed by mjpost** 2019-10-11 17:48 UTC
