### ISSUE TITLE
Correction to Anthology ID 2020.nlp4convai-1.13

### ISSUE THREAD

**Issue by al3xpapangelis** [acl-org/acl-anthology#919] opened 2020-07-10 17:01 UTC
**Please be sure to add the Anthology ID in the title**

2020 NLP4CONVAI Paper #25: MultiWOZ 2.2 : A Dialogue Dataset with Additional Annotation Corrections and State Tracking Baselines

https://www.aclweb.org/anthology/2020.nlp4convai-1.13/

## Metadata correction: please describe the issue here**

Wrong author list. 

The correct author list is: Xiaoxue Zang, Abhirast Rastogi, Srinivas Sunkara, Raghav Gupta, Jianguo Zhang, Jindong Chen.

## Revision or erratum: please add the following information**

- [ ] I have attached the revised PDF or erratum to this issue
- [ ] I have written a brief description of the changes below

The brief description of the changes will be displayed on your paper page, and should be written in a neutral (third-person) fashion with complete sentences. For example:

> This revision corrects a typo in Equation 7. It also introduces a new figure, Figure 12, which plots the relationship between our proposed model and the baselines.

**Description of changes**

**Comment by mjpost** [comment] 2020-08-10 23:48
Hi, apologies for the delay in responding, but it took some time for us to determine our policy. Many conferences do not permit changes to the author list, so we require permission from the relevant program chairs or workshop organizer. Please arrange for this permission to be sent to me at anthology@aclweb.org, or to be added here, along with some evidence that the person posting is authorized (i.e., link to website with list of conference organizers).

**Comment by mjpost** [comment] 2020-08-11 00:41
Duplicate of #880.

**Closed by mjpost** 2020-08-11 00:41 UTC
Labels: metadata

**Comment by al3xpapangelis** [comment] 2020-08-11 02:03
Hi Matt,

I’m a PC for NLP4Convai: https://sites.google.com/view/2ndnlp4convai/organisers <https://sites.google.com/view/2ndnlp4convai/organisers> and we’re happy to do the author change. Please let me know if you need anything more.

Thanks,
Alexandros Papangelis

**Comment by mjpost** [comment] 2020-08-11 03:25
Okay, great, thank you!
