### ISSUE TITLE
Cannot advance or sort search pages

### ISSUE THREAD

**Issue by rightaditya** [acl-org/acl-anthology#88] opened 2018-10-17 04:21 UTC
I'm having trouble advancing through the search pages, as well as sorting them.

To reproduce, search the anthology for something. If I try "lstm" I get an error result: "The page you were looking for doesn't exist. You may have mistyped the address or the page may have moved."

If I try "supertagging" I get a correct result page, but if I try to re-sort it by year, or go to the second page, I get the same error as above.

**Comment by villalbamartin** [comment] 2018-10-17 07:43
Thanks for the bug report. I believe it might be an issue with the Solr search backend. I'm looking into it.

**Comment by villalbamartin** [comment] 2018-10-17 09:10
Update on this issue: we recently changed the passwords for the database, and we forgot to change it for Solr specifically. As a result, Solr was using the old cached index. I am rebuilding the index now, which takes a bit. Hopefully that will solve the issue.

**Comment by villalbamartin** [comment] 2018-10-17 09:15
The issue is solved now. Closing it.

**Closed by villalbamartin** 2018-10-17 09:15 UTC

**Comment by rightaditya** [comment] 2018-10-17 20:53
@villalbamartin Thanks for addressing it so quickly!
