### ISSUE TITLE
Metadata correction for 2024.iwclul-1.13

### ISSUE THREAD

**Issue by slowwavesleep** [acl-org/acl-anthology#4274] opened 2024-12-30 17:40 UTC
### JSON data block

```json
{
  "anthology_id": "2024.iwclul-1.13",
  "title": "Prune or <fixed-case>R</fixed-case>etrain: <fixed-case>O</fixed-case>ptimizing the <fixed-case>V</fixed-case>ocabulary of <fixed-case>M</fixed-case>ultilingual <fixed-case>M</fixed-case>odels for <fixed-case>E</fixed-case>stonian"
}
```

**Comment by nschneid** [comment] 2024-12-30 18:55
Duplicate of #4246 (`<fixed-case>` should not be used for common nouns)

**Closed by nschneid** 2024-12-30 18:55 UTC
Labels: correction, metadata
