### ISSUE TITLE
Ingestion Request [05-14-2024]:  LREC-COLING 2024

### ISSUE THREAD

**Issue by fcbond** [acl-org/acl-anthology#3175] opened 2024-04-01 14:11 UTC
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [X] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

lrec, coling

### Volume Title

Proceedings of the 2024 Joint International Conference on Computational Linguistics, Language Resources and Evaluation  (LREC-COLING 2024)

### Date of Publication

2024-05-14

### Supporting Information

Hi,

I am in charge of this, along with @arademaker.   It is going to be massive, over 1,558 papers in the main conference, plus tutorials and 36 workshops (originally 38, one was merged one was cancelled).

1. There are many workshops, 30 with existing venues, 7 with new ones (some are joint).  We attach a spreadsheet with the complete list, and a summary here.   Do we need an issue for each new workshop venue?
    *  W9 is joint between FinNLP, econlp and KDF (KDF is not in venues)
    *  W10 is joint between MWE and UD
3. We have ISBNs for the proceedings, tutorials and all the workshops (from ELRA) included in the attached spreadsheet.
4.  Coling and LREC both have ISSNs, we would like to use both:  2951-2093, 2522-2686 
     [not in the ACL anthology metadata although it would be good to have: is there anywhere to note this?]

Please help us with this mammoth undertaking!

Francis @fcbond

New workshop venues:
```
neusymbridge
delite
determit
dlnld
htres
polp
rfp
safei
```

All workshop venues (two workshops are joint): 
```
rapid
neusymbridge
delite
determit
dlnld
games
htres
finnlp
mwe
udw
legal
mathnlp
nlperspectives
parlaclarin
polp
politicalnlp
rfp
cawl
sigul
signlang
bucc
isa
eurali
readi
econlp
osact
wildre
ldl
dmr
rail
humeval
ecnlp
unlp
safeai
cogalex
lt4hala
trac
tdle

```
[Proceedings titles for  LREC-COLING 2024 final.xlsx](https://github.com/acl-org/acl-anthology/files/15282147/Proceedings.titles.for.LREC-COLING.2024.final.xlsx)

**Comment by helenemazo** [comment] 2024-04-02 10:35
1. Workshops venue:  the venue is the same for the conference and all workshops/Tutorials = Lingotto Conference Center in Turin (Italy)
2. The ISBN for the tutorials should be: 978-2-493814-35-7 (to be confirmed)
3. The ISSN number goes with the ISBNs. Please use the LREC ISSN: 2522-2686
4. Let me check this with Khalid and come back to you.
Best,
Hélène

**Comment by fcbond** [comment] 2024-04-02 11:00
`venue` is the acl-anthology term for the series  the proceedings is associated with: https://aclanthology.org/venues/

I am checking with the ISSN authority if we can use both ISSNs.

Also, it looks as though two workshops have merged, I will send a new spreadsheet as soon as I know the details.

**Comment by fcbond** [comment] 2024-04-02 12:00
We want to use both ISSNS: 2522-2686,  2951-2093

I have verified that this is ok:

>Yours is a particular case, you can identify this year joint proceedings with both ISSN. As it is a one-shot joint conference, a new ISSN assignment is not neccesary.
> 
> We havea added a note to the LREC Proceedings record: 2024 conference, entitled "Joint International Conference on Computational Linguistics, Language Resources and Evaluation" held jointly with "International conference on computational linguistics" ISSN 2951-2093, that clarifies the issue.

From the ISSN International Centre
Metadata and Technical Coordination of the ISSN Network Department

**Comment by arademaker** [comment] 2024-04-13 02:36
What acronym should we use for the LREC-COLING 2024? Both events have their acronyms:

1. https://aclanthology.org/venues/lrec/
2. https://aclanthology.org/venues/coling/

Eventually, they will become separated again. Does it make sense to have one new acronym for the joint event? but the links above will both miss the 2024 edition.

**Comment by mbollmann** [comment] 2024-04-13 09:41
> What acronym should we use for the LREC-COLING 2024? Both events have their acronyms:

Proceedings can have multiple venues assigned to them, so it can appear on both.

**Comment by fcbond** [comment] 2024-04-13 09:45
Thank you.  When we use ACLpub in softconf, should the abbreviation be the venue name, or is that unconnected?   If they are connected, how do we write mulitple cenues? `lrec,coling`?

**Comment by mbollmann** [comment] 2024-04-15 14:22
I know what it can/should look like in our XML, but I don’t know anything about ACLpub, unfortunately. Maybe @mjpost knows.

**Comment by mbollmann** [comment] 2024-04-15 14:32
You probably shouldn’t see the venue question as a blocker, though, since it’s an easy one-line change in our XML if it turns out wrong (I hope @mjpost or @anthology-assist won’t crucify me for saying this :)). [ACL-IJCNLP 2021](https://aclanthology.org/2021.acl-long.0/) is an example for how this will look in the end.

**Comment by fcbond** [comment] 2024-04-15 14:33
Thanks @mbollmann, 

We will try to get the files to you as quickly as possible, so that you can look at issues there.

There is one question it would be very helpful to answer now.  We have 5 new venues.  **Do we need an issue for each new workshop venue?**  Or is this single issue enough?

There have been a couple of changes, I will update the original issue to match the current state (two workshops got merged, we have multiple ISSNS, etc.)

Thanks again for your help,

**Comment by mbollmann** [comment] 2024-04-15 14:34
What I do realize now (sorry for spamming multiple messages) is that the Anthology IDs will only reflect one of the venues though; as for example ACL-IJCNLP papers have `2021.acl-*` IDs. Do you have a strong preference for having both venues in the _ID_ itself?

**Comment by fcbond** [comment] 2024-04-15 14:40
Hi,

I think the id is just an ID, we don't have a strong preference (at least I don't).

**Comment by mjpost** [comment] 2024-04-15 16:10
Hi, thanks for tagging me, I am just seeing this.

One issue is fine as @mbollmann mentions.

As for venue ID (lrec vs. coling), we can associated the proceedings with both venues, so that it will appear jointly on both pages. But you have to choose one, which will be used in the filename.

**Comment by anthology-assist** [comment] 2024-04-30 18:20
Just waiting on the final venue ID and the ingestion material.

**Comment by arademaker** [comment] 2024-05-02 13:15
I remember we can now make a PR with the files, right?

**Comment by anthology-assist** [comment] 2024-05-02 19:53
@arademaker @fcbond When ingestion material is ready, you can share the google drive folder link with the .tgz files directly here!

**Comment by AlongWY** [comment] 2024-05-03 04:47
Dear Team and Prof. Bond,

We've identified an error in the author affiliation for our paper and would like to request a correction. We apologize for the oversight and appreciate your assistance in updating the information.

## Paper Details:

+ Title: "Improving Language Model Reasoning with Self-motivated Learning"
+ Submission Number: 1033
+ Affected Author: Wanxiang Che

## Correction Needed:
The current listing incorrectly shows Wanxiang Che's affiliation as "Huawei Noah’s Ark Lab." The correct affiliation should be "Harbin Institute of Technology."

Please let us know how to proceed with the submission of the revised paper and any other necessary steps to complete the correction.

Thank you for your help.

Best,
Yunlong Feng
[paper-1033.pdf](https://github.com/acl-org/acl-anthology/files/15196300/paper-1033.pdf)
[paper-1033-source.zip](https://github.com/acl-org/acl-anthology/files/15196302/paper-1033-source.zip)

**Comment by arademaker** [comment] 2024-05-10 22:17
Hi @anthology-assist  

here are the links

1. all papers https://softconf.com/lrec-coling2024/papers/pub/aclpub/proceedings.tgz
2. tutorials https://softconf.com/lrec-coling2024/tutorials/pub/aclpub/proceedings.tgz
3. link for the google drive with the workshops proceedings https://drive.google.com/drive/folders/1vBHJGWrgxWyAo5HgvzE6QGnbt1Xrt-ES?usp=sharing

We would like to have the event listed in both

1. https://aclanthology.org/venues/lrec/
2. https://aclanthology.org/venues/coling/

For the event itself, we expect something like

https://aclanthology.org/events/lrec-2022/ listing 

1. the proceedings of the papers
2. the proceedings of the tutorials
3. the 36 workshops from the Google Driver (see that 03 and 25 were cancelled)

**Comment by arademaker** [comment] 2024-05-10 22:19
Can you guys start the ingestion? We have 10 days for the conference: https://lrec-coling-2024.org/. It would be really nice if people can have the files in the ACL Anthology during the conference.

**Comment by anthology-assist** [comment] 2024-05-11 01:55
> Hi @anthology-assist
> 
> here are the links
> 
> 1. all papers [here](https://softconf.com/lrec-coling2024/papers/pub/aclpub/proceedings.tgz)

This link does NOT work.

> 2. tutorials [here](https://softconf.com/lrec-coling2024/tutorials/pub/aclpub/proceedings.tgz)
> 3. link for the google drive with the workshops proceedings [here](https://drive.google.com/drive/folders/1vBHJGWrgxWyAo5HgvzE6QGnbt1Xrt-ES?usp=sharing)

So far I found W03 is missing. Could you double check all workshops are present?

> 
> We would like to have the event listed in both
> 
> 1. https://aclanthology.org/venues/lrec/
> 2. https://aclanthology.org/venues/coling/
> 
> For the event itself, we expect something like
> 
> https://aclanthology.org/events/lrec-2022/ listing
> 
> 1. the proceedings of the papers
> 2. the proceedings of the tutorials
> 3. the 36 workshops from the Google Driver (see that 03 and 25 were cancelled)

**Comment by fcbond** [comment] 2024-05-11 08:16
Hi,

Hi @anthology-assist <https://github.com/anthology-assist>
>
> here are the links
>
>    1. all papers here
>    <https://softconf.com/lrec-coling2024/papers/pub/aclpub/proceedings.tgz>
>
> This link does NOT work.
>
Sorry, I think softoncf rebuilt it one last time (which takes over an
hour).  It is there now.


>
>    2. tutorials here
>    <https://softconf.com/lrec-coling2024/tutorials/pub/aclpub/proceedings.tgz>
>    3. link for the google drive with the workshops proceedings here
>    <https://drive.google.com/drive/folders/1vBHJGWrgxWyAo5HgvzE6QGnbt1Xrt-ES?usp=sharing>
>
> So far I found W03 is missing. Could you double check all workshops are
> present?
>
W03 was cancelled.   I will update the list.

We would like to have the event listed in both
>
>    1. https://aclanthology.org/venues/lrec/
>    2. https://aclanthology.org/venues/coling/
>
> For the event itself, we expect something like
>
> https://aclanthology.org/events/lrec-2022/ listing
>
>    1. the proceedings of the papers
>    2. the proceedings of the tutorials
>    3. the 36 workshops from the Google Driver (see that 03 and 25 were
>    cancelled)
>
>
Yours,

-- 
Francis Bond <https://fcbond.github.io/>

**Comment by fcbond** [comment] 2024-05-11 08:24
I have updated the information and the attachment in the first comment.

**Comment by arademaker** [comment] 2024-05-11 20:41
dear @anthology-assist 

Here is the list of the links for the proceedings updated with all `meta` file revised.

Tutorials and main papers:

```
https://softconf.com/lrec-coling2024/tutorials/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/papers/pub/aclpub/proceedings.tgz
```

Workshops. We are still working to have 3 remaining workshop files that will need to be produced offline by their organizers. We will update here as soon as they send us the new version.

```
https://softconf.com/lrec-coling2024/cawl2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/cl4health2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/cogalex2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/determit2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/dlnld2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/dmr2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/ecnlp-7/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/eurali2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/finnlp-kdf2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/gamesandnlp2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/htres2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/humeval2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/isa2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/ldl2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/legal2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/lt4hala2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/mathnlp2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/mwe-ud2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/neusymbridge2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/nlperspectives2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/osact2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/parlaclarin-iv/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/politicalnlp2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/rail2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/rapid2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/readi2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/reference-framing-perspective2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/safeconvai2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/sigul2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/tdle2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/trac2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/unlp2024/pub/aclpub/proceedings.tgz
https://softconf.com/lrec-coling2024/wildre-7/pub/aclpub/proceedings.tgz
```

**Comment by anthology-assist** [comment] 2024-05-12 18:48
@fcbond The main and tutorials volums, and most of the workshops have been ingested here #3293. Please take a look at the preview and let us know if anything looks wrong (you can leave comment directly on that PR).

There are several workshops contain wrong meta file information hence they aren't ingested -- W7, W8, W9, W13, W16, W17, W38. Please correct them.

**Comment by fcbond** [comment] 2024-05-12 19:32
Thank you!

We had noticed some errors, and have been correcting them all weekend.   When they are done we will let you know.

We will leave new comments on the PR.

**Comment by arademaker** [comment] 2024-05-12 20:15
@anthology-assist what are the errors? I have just fixed all the URL field and one shortbooktitle field. We are still waiting 03, 20 and 21, the only ones we can't fix ouselves in the softconf system.

**Comment by arademaker** [comment] 2024-05-31 15:38
according to https://aclanthology.org/faq/

> How does the ACL Anthology use Digital Object Identifiers (DOIs)?
> ... Note while the ACL Anthology hosts third-party materials coming from sister societies, these materials are hosted courtesy the ACL but are not assigned DOIs by the ACL due to costs and copyright limitations; the DOI information above is only applicable to ACL sponsored events by ACL, its chapters or SIGs.

I guess LREC, COLING and many of its workshops would be eligible for getting DOI, right? What is the proper way to add DOI for all papers in the LREC-COLING 2024 and its workshops?

**Comment by mjpost** [comment] 2024-05-31 15:42
DOIs cost $1 to mint. We can do this for you under the Anthology identifier and arrange for you to reimburse ACL. A simpler process would be for you to generate them and then give us a list of (Anthology ID, DOI) pairs, that we could then add to the papers.

We use the following two scripts to generate DOIs that may be helpful to you if you choose route 2:

* Generate the Crossref XML: https://github.com/acl-org/acl-anthology/blob/master/bin/generate_crossref_doi_metadata.py. This is then uploaded to their site and DOIs generated.

* Inject the assigned DOIs into the Anthology XML: https://github.com/acl-org/acl-anthology/blob/master/bin/add_dois.py. This script verifies that the DOI URLs resolve, so it is pretty robust.

**Comment by fcbond** [comment] 2024-06-02 11:35
Thanks @mjpost, we will check with the general chairs and get back to you as soon as we can.

**Comment by marcschulder** [comment] 2024-06-04 16:35
It appears two workshops got ingested but didn't make it onto the event's list of volumes: [signlang](https://aclanthology.org/volumes/2024.signlang-1/) and [BUCC](https://aclanthology.org/volumes/2024.bucc-1/) are missing from [lrec-2024](https://aclanthology.org/events/lrec-2024/) and [coling-2024](https://aclanthology.org/events/coling-2024/)

**Comment by arademaker** [comment] 2024-06-14 19:50
Dear all, 

In the first page of https://aclanthology.org/2024.mwe-1.0.pdf my surname is incorrect "Rademacher" instead of "Rademaker".  Can you guys fix? Possible recompiling the PDF?

**Comment by arademaker** [comment] 2024-06-14 20:45
The new version of the MWE-UD proceedings is here:

https://drive.google.com/file/d/1IrGrkcdVv8BOgP5nCy--Cginu93NE8eY/view?usp=drive_link

**Comment by anthology-assist** [comment] 2024-06-26 13:20
@arademaker If the changes only occur on two pages within 1 pdf, we do not need to perform a reingestion. Could you submit a [correction ticket](https://aclanthology.org/info/corrections/) for the name spelling update?

**Closed by anthology-assist** 2024-06-26 13:20 UTC
Labels: ingestion, pending
