### ISSUE TITLE
Inconsistencies of entry types of workshop paper

### ISSUE THREAD

**Issue by buechel** [acl-org/acl-anthology#33] opened 2017-02-15 13:32 UTC
I noticed that for papers in workshop proceedings the bib-file sometimes uses the entry type "inbook" (which from my point of view doesn't make sense) while for other "inproceedings" is used.

Compare http://aclanthology.info/papers/feelings-from-the-past-adapting-affective-lexicons-for-historical-emotion-analysis.bib and http://aclanthology.info/papers/semeval-2007-task-14-affective-text.bib

**Comment by knmnyn** [comment] 2017-12-27 01:53
Now a duplicate of #46, will solve there.

**Closed by knmnyn** 2017-12-27 01:53 UTC

**Comment by knmnyn** [comment] 2018-01-06 16:27
@buechel this has been solved now, by @danielgildea 's PR which has been merged.  Thanks for your bug report !
