### ISSUE TITLE
Request to update my name, as an author

### ISSUE THREAD

**Issue by rspeer** [acl-org/acl-anthology#117] opened 2019-01-22 21:36 UTC
ACL Anthology IDs: S18-1162, S17-2008

These are two papers that currently appear on the ACL Anthology under the name "Robert Speer". Since the time I wrote those papers, I've changed my name, for all purposes, to Robyn Speer. I prefer not to be identified by my old name, including in citations, so I would like to request a revision to these papers.

This requires a change to the content of the papers as well:

- The updated paper for S17-2008 is: http://s3.amazonaws.com/rspeer-acl-updates/S17-2008.pdf
- The updated paper for S18-1162 is: http://s3.amazonaws.com/rspeer-acl-updates/S18-1162.pdf

Only the author line and bibliography have been changed in each.

L12-1639 is one more paper that I would prefer to revise to update my name, but at the moment, I can't supply the corresponding PDF change because I haven't been able to find the original LaTeX of the paper.

**Comment by mjpost** [comment] 2019-01-27 18:22
This should easy to do. It would be convenient to process these all at once; do you have any updates on L12-1639? It would be ideal to correct the paper yourself, but if you can’t find it, we could just update the paper’s metadata.

When you are ready, can I ask you to make the changes yourself and issue a pull request? [I’ve written up some instructions here](
https://github.com/acl-org/acl-anthology/wiki/Issuing-Pull-Requests-For-Corrections).

**Comment by rspeer** [comment] 2019-01-28 21:48
Thanks. I've still been unable to find the source of L12-1639. Changing just the metadata would be acceptable.

I'll try making the pull request.

**Comment by rspeer** [comment] 2019-01-28 21:54
This repo only covers the metadata, not the PDF files themselves, right?

**Comment by rspeer** [comment] 2019-01-29 17:37
The pull request is open and my co-authors have commented there to give their assent.

**Comment by mjpost** [comment] 2019-01-29 20:34
Done. This will not be live until the next time the site gets regenerated (within the next few days).

**Comment by rspeer** [comment] 2019-01-29 22:30
Thank you!

**Comment by rspeer** [comment] 2019-02-07 21:24
@mjpost There's still more that needs to be updated, it seems. See #132.

**Comment by mjpost** [comment] 2019-02-10 17:35
I’m going to reopen this issue until we resolve the linked papers. I’m not quite sure of the mechanics here and we should think about it for the static rewrite.

**Comment by villalbamartin** [comment] 2019-02-11 16:19
I have regenerated the site, but even though there are now two links to `Revision v1` and `Revision v2` (working as expected), the `URL` field in the website still points to the original paper. We can either...

1. ... change the PDF file in `aclweb.org`
2. ... change the URL field in the XML file, or
3. ... change the code of the website so `URL` always picks the latest revision of a paper

Similarly, should we update the DOI field too?

**Comment by knmnyn** [comment] 2019-02-11 16:52
Hi all:

This "feature" is by design.  As per the ACL Anthology's previous policies,
revisions do not invalidate the original paper so only revisions are
posted, but the original DOI and the canonical address resolve to the
original paper.

Of course, if the current Director wishes to change this, that is not a
problem.  Matt is within his scope and directive to change this setting.
For the DOIs, Matt will need to update the DOI information for the paper to
point appropriately, or have the original paper be accessible through
something like S17-2008v1.pdf and then have S17-2008 redirect to the
current S17-2008vX.pdf where X is the current revision level.

Cheers,

Min

--
Min-Yen KAN (Dr) :: Associate Professor :: National University of Singapore
:: NUS School of Computing, AS6 05-12, 13 Computing Drive
Singapore 117417 :: +65 6516 1885(DID) :: +65 6779 4580 (Fax) ::
kanmy@comp.nus.edu.sg (E) :: www.comp.nus.edu.sg/~kanmy (W)

**Comment by mjpost** [comment] 2019-02-12 02:55
Thanks, Min. It seems sensible to me that we should take your advice here and return the latest revision posted. This preserves the archival and non-invalidation role of the Anthology while also better reflecting author intent, and also brings us in line the behavior of other archival sites, such as the arXiv.

I cannot decide the best way to handle this. I would like to avoid the paperwork of updating DOIs, however, and it makes sense for the "generic" accessor (e.g., http://aclweb.org/anthology/S18-1162) to return the latest version. So my thinking is that (a) the web page should generate links to all revision (v1, v2, etc) and (b) when a first PDF revision is posted, we move the original file to the "v1" extension, create the "v2" version, and then also copy the "v2" version to the base file name.

**Comment by knmnyn** [comment] 2019-02-12 16:08
Hi Matt, all:

I agree that keeping the DOI and the generic accessor works best, because
this doesn't invalidate the canonicalization.  The separate layer of
indirection that is implemented within the Anthology now already implicitly
redirects (without URL rewrite) the canonical URL to the .pdf.  I would
suggest writing that layer with more programmatic checks to re-direct it to
the most recent copy.

The implicit redirects are only apparent on the actual aclweb.org host (see
the .htaccess file in the old_anthology subdir which specifies the
"RewriteRule"s.
Some of the redirects are very old, appearing before my tenure of the
Anthology, when Drago's RA helped Steven add in the logic.

Min

**Comment by mjpost** [comment] 2019-02-19 03:51
Okay, this now seems to be working, and [the corrections page has been updated](https://aclanthology.info/corrections) (pending a site rebuild) to reflect the new policy.

@villalbamartin, can you rebuild the site? There are a very large number of corrections that have been pushed up in the past few days, so you may want to take care with the database and search re-indexing.

Once that's done, we can close this issue.

**Comment by rspeer** [comment] 2019-02-19 16:36
Thanks for the update! I don't know if this is one of the things that's waiting for the rebuild, but I noticed that the bibtex on L12-1639 still contains my old name.

**Comment by mjpost** [comment] 2019-02-19 17:32
[The metadata](https://github.com/acl-org/acl-anthology/blob/7a24dfe734b21e0b7952b26f67b328685a7d3b73/import/L12.xml#L8605) is correct; It's just that the site hasn't been rebuilt.

**Comment by villalbamartin** [comment] 2019-02-20 18:39
@mjpost I've rebuilt now the website with all export formats.

**Comment by mjpost** [comment] 2019-02-20 18:53
Thanks, Martín. This looks good, except it looks [the venue page](https://aclanthology.info/events/semeval-2017) didn't update (Ctrl-F "Speer" shows the old name). How do we regenerate that page?

**Comment by villalbamartin** [comment] 2019-02-21 20:23
I forgot to regenerate the cache. It is now done, and all other pages in the cache are also being regenerated.

**Closed** 2019-02-22 10:53 UTC
Labels: correction
