### ISSUE TITLE
Ingestion request

### ISSUE THREAD

**Issue by anacastrosalgado** [acl-org/acl-anthology#2337] opened 2023-01-12 09:44 UTC
Dear Sirs, 
1) I created a ticket on 21st November registering our intention to submit our proceedings for LDK2023:
[(https://github.com/acl-org/acl-anthology/issues/2251)]

2) We also want to confirm if the last version of the ACL Paper Styles is here:
[(https://github.com/acl-org/acl-style-files)]

Thanks in advance.
Ana Salgado

**Comment by mjpost** [comment] 2023-01-12 21:26
Yes, those should be the latest style files.

Closing as duplicate of #2251.

**Closed by mjpost** 2023-01-12 21:26 UTC
