### ISSUE TITLE
Author Metadata: {Phil Sidney Ostheimer}

### ISSUE THREAD

**Issue by PhilSid** [acl-org/acl-anthology#3816] opened 2024-08-26 12:38 UTC
### Author Pages

https://aclanthology.org/people/p/phil-ostheimer/
https://aclanthology.org/people/p/phil-sidney-ostheimer/

### Type of Author Metadata Correction

- [ ] The author page wrongly conflates different people with the same name.
- [X] This author has multiple pages with different spellings of their name.
- [ ] This author has permanently changed their name.

### Supporting Information

Hi,

could you please merge my author pages https://aclanthology.org/people/p/phil-ostheimer/ and https://aclanthology.org/people/p/phil-sidney-ostheimer/ into the latter one (https://aclanthology.org/people/p/phil-sidney-ostheimer/)?My middle name is somehow missing.

There is already an unresolved issue: https://github.com/acl-org/acl-anthology/issues/3532

**Comment by mbollmann** [comment] 2024-08-26 13:28
Duplicate of #3532

**Closed by mbollmann** 2024-08-26 13:28 UTC
Labels: correction, author-page
