### ISSUE TITLE
Papers are out of sync in W04-13, maybe others (W04-19, W11-11?)

### ISSUE THREAD

**Issue by davidweichiang** [acl-org/acl-anthology#141] opened 2019-02-15 22:09 UTC
For example, if you look [here](https://www.aclweb.org/anthology/W/W04/#1300), the first paper (W04-1302) is by Buttery, but if you click on it, it's by Cavar et al. Same for W04-19. Not W11-11, though (that has a different issue). W04-30 also has a syncing problem with the last two papers.

**Comment by mjpost** [comment] 2019-02-16 14:34
This is a duplicate of #128. I pull in some of these issues to that one.

**Comment by davidweichiang** [comment] 2019-02-16 14:46
I’d be happy to correct this by hand if you can confirm that the ids in the xml are the ones that should change. Otherwise, I don’t know how to fix it. 

Going forward, the diff script I am using could be used as an automatic check. In these cases, the bib was in sync with the pdf, so no fancy pdf processing is necessary.

**Comment by mjpost** [comment] 2019-02-16 14:54
I think it will require hand correction. What I am trying to decide is whether the PDFs are off by 1, or the metadata. I'm hoping it's the metadata, looking now.

**Comment by mjpost** [comment] 2019-02-16 15:00
If you look at W04-01* for example, paper ID 00 is the front matter, and 01 the first paper in the volume. This seems to be the general trend; it isn't conventional to list the introduction as a separate paper. Also, there is only one PDF for two metadata pieces (W04-00 and W04-01). So I think the mistake is having a separate entry in the metadata, and we should delete the the current 1301 (Sakas), shifting everything after it down by 1.

**Comment by davidweichiang** [comment] 2019-02-16 15:07
Do you mean that the change you describe should happen in the xml? I can take care of that. 

Can you check the other two workshops too? I believe the one that goes out of sync towards the end involves a missing real (withdrawn?) paper.

**Comment by mjpost** [comment] 2019-02-16 15:24
Yes, [in the XML](https://raw.githubusercontent.com/acl-org/acl-anthology/master/import/W04.xml), thanks!

Looking over the other two now.

**Comment by mjpost** [comment] 2019-02-16 15:28
One small correction: I think W04-1300 and W04-1301 should be merged—i.e., the author credit for the front matter should go to the organizer. This seems to follow the convention for the main conference.

**Comment by mjpost** [comment] 2019-02-16 15:30
Same for W04-19: Merge the entries for [1900](https://github.com/acl-org/acl-anthology/blob/4744520b8cbdf21a8f6b46471f6cc6efdd96bc93/import/W04.xml#L2122) and 1901 (keep the title from 1900, and the authors from 1901).

**Comment by mjpost** [comment] 2019-02-16 15:43
For W04-30, [the schedule](http://aclweb.org/anthology/W04-3000) lists:

- ...
- Speech Recognition Models of the Interdependence Among Syntax, Prosody, and Segmental Acoustics (correctly assigned 3010)
- Modeling Prosodic Consistency for Automatic Speech Recognition: Preliminary Investigations (missing entirely from metadata)
- Assigning Domains to Speech Recognition Hypotheses  (assigned 3011 in metadata, should be 3012)
- Context Sensing using Speech and Common Sense (assigned 3012 in metadata, should be 3013)

The original associated [PDFs](http://aclweb.org/anthology/W04-3011.pdf) and [bibs](http://aclweb.org/anthology/W04-3011.bib) are all there. So it seems that this was just ingested incorrectly.

They all need to be corrected but it looks like the errors are in ingest, not in the original bibs. So we should add "Modeling Prosodic Consistency for Automatic Speech Recognition: Preliminary Investigations" (Ernest Pusateri and James Glass) as entry 3011, and shift the other two after it to accommodate it.

Fixing many of these workshop imports similar [to what you did here](https://github.com/acl-org/acl-anthology/pull/140) seems to be something we should look at next.

**Comment by mjpost** [comment] 2019-02-16 20:36
Reopening until the issues are fixed since the discussion accumulated here instead of #128.

**Closed** 2019-02-17 21:08 UTC
Labels: correction
