### ISSUE TITLE
Non-ACL events prior to 2000 are 404

### ISSUE THREAD

**Issue by danielgildea** [acl-org/acl-anthology#40] opened 2017-11-02 18:02 UTC
links to pdfs give a not found error, for example:
https://aclanthology.info/pdf/C/C98/C98-1001.pdf

**Comment by knmnyn** [comment] 2017-11-07 01:35
Hi Dan:

Thanks for the report.  We'll try to get this corrected over the next few days.  Apologies as we are busy towards the end of the semester (exam prep, etc.).

**Comment by knmnyn** [comment] 2017-11-08 01:51
Hi Martín, Christoph: the problem is that the URLs for the PDFs point to coli.uni-saarland.de instead of using the canonical repository at aclweb.org.  Can you change all of the PDF references to point to the http://www.aclweb.org/anthology/<Anthology-ID>?

**Comment by knmnyn** [comment] 2017-11-08 01:52
Will fix #43 as well.  Please check and close when this issue is fixed.

**Comment by knmnyn** [comment] 2017-11-12 07:51
Hi all:
I've copied over some of the files for all series except for W (there's not enough space on the coli.uni-saarland server.)  So at least most of the files that @danielgildea mentioned should be operational now.

Not closing this issue but the actual instance should be fixed now.

**Comment by villalbamartin** [comment] 2017-11-15 11:24
The links are now redirecting to aclweb.org, so the main issue is now solved. The .bib files should be regenerated soon.
Closing the issue now.

**Closed by villalbamartin** 2017-11-15 11:24 UTC
Labels: urgent
