### ISSUE TITLE
Formatting issue in LREC-COLING proceedings

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#3305] opened 2024-05-18 17:10 UTC
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

Partway down https://aclanthology.org/events/coling-2024/ we see a stray bold tag that messes with layout:

<img width="813" alt="image" src="https://github.com/acl-org/acl-anthology/assets/985263/e795913e-aaa5-4bc7-b2c9-4876f1c0101e">

**Comment by mbollmann** [comment] 2024-05-18 17:29
The cause is probably an empty `<b/>` tag in the preceding paper's abstract.

That’s really tricky, as it’s not disallowed by the XML schema (`text` can be the empty string), but also not easily enforceable in the schema (replacing `text` by a pattern like `xsd:string {minLength="1"}` results in an error in compiling the schema, most likely due to [an inherent limitation of RELAX NG](https://stackoverflow.com/a/5047555)).

We should probably add an explicit check for these edge cases _somewhere_, though.

**Comment by akoehn** [comment] 2024-05-18 17:48
This really is tricky, as the proper test would be that the string neither does a *net* close nor open of a tag, while tags themselves are allowed. This is probably not achievable via a fsa and therefore relaxng; it would need to be checked on read time in python.

**Comment by mbollmann** [comment] 2024-05-18 18:02
> Edit: what I wrote needs to be checked as well, but I misread b/ as /b -- I frankly don't even understand why that breaks the rendering.

Closing tags are mandatory in HTML 5, I believe, except for a pre-defined list of "void" elements such as `<br />`. Since "b" is not a void element, I guess the browser engines "correct" the `<b/>` into a plain opening `<b>` tag.

**Comment by nschneid** [comment] 2024-05-18 18:11
If `<b/>` or `<i/>` etc. occur in an abstract it's probably an error, so it would be good to flag it.

**Comment by mbollmann** [comment] 2024-05-18 18:11
[XHTML 1.0 says](https://www.w3.org/TR/xhtml1/#C_3):

> Given an empty instance of an element whose content model is not EMPTY (for example, an empty title or paragraph) do not use the minimized form (e.g. use `<p> </p>` and not `<p />`).

[HTML 5 says](https://www.w3.org/TR/2011/WD-html5-20110405/syntax.html#start-tags) about the structure of start tags:

> Then, if the element is one of the [void elements](https://www.w3.org/TR/2011/WD-html5-20110405/syntax.html#void-elements), or if the element is a [foreign element](https://www.w3.org/TR/2011/WD-html5-20110405/syntax.html#foreign-elements), then there may be a single U+002F SOLIDUS character (/). This character has no effect on [void elements](https://www.w3.org/TR/2011/WD-html5-20110405/syntax.html#void-elements), but on [foreign elements](https://www.w3.org/TR/2011/WD-html5-20110405/syntax.html#foreign-elements) it marks the start tag as self-closing.

In other words, for "normal elements" such as `<b>`, it does _not_ say that the slash marks it as self-closing...

(I may have gone a bit overboard digging into this.)

**Closed** 2024-05-21 21:36 UTC
Labels: bug
