### ISSUE TITLE
Ingestion Request: LDK (09-12-2023)

### ISSUE THREAD

**Issue by anacastrosalgado** [acl-org/acl-anthology#2655] opened 2023-07-17 16:18 UTC
### General information about this request

- [X] I confirm that I have read the [Information for Submitters](https://aclanthology.org/info/contrib/).
- [ ] I am submitting a request for a **new venue** that does not exist in the ACL Anthology yet.

### Venue Identifier

LDK

### Volume Title

​Proceedings of the 4th Conference on Language, Data and Knowledge (LDK)

### Venue Name (only if you are submitting a new venue)

Conference on Language, Data and Knowledge

### Venue Website (only if you are submitting a new venue)

http://2023.ldk-conf.org/

### Date of Publication

12 September 2023

### Supporting Information

In November last year, I created an issue ([(https://github.com/acl-org/acl-anthology/issues/2251)]) asking for three different sub-volumes for the LDK conference. Could you let me know if changing the number of three to two sub-volumes is possible? The reason for this changing is that the volume of short papers was much lower than expected.

**Venue Identifier:** LDK
**Volume Title: ​**Proceedings of the 4th Conference on Language, Data and Knowledge (LDK)
**Sub-Volumes Title:**
Proceedings of the 4th Conference on Language, Data and Knowledge (LDK): Papers
Proceedings of the 4th Conference on Language, Data and Knowledge (LDK): Workshops/Tutorials
**Venue Name:** Conference on Language, Data and Knowledge
**Website:** http://2023.ldk-conf.org/
**Publication date:** 12 September 2023

Waiting for your approval,
Ana Salgado

**Comment by anthology-assist** [comment] 2023-07-26 01:02
@mjpost Could you approve this?

@anacastrosalgado Please submit ingestion material two weeks prior to the publication date.

**Comment by mjpost** [comment] 2023-07-26 13:16
This is a duplicate of #2251, right? Let's just keep that one. It is fine to have just two volumes. Note however that this *is* a new venue. The Venue ID "ldk" is fine.

**Closed by mjpost** 2023-07-26 13:16 UTC
Labels: ingestion

**Comment by anacastrosalgado** [comment] 2023-07-26 13:50
@mjpost Yes, Matt. We decided to have two volumes.
