### ISSUE TITLE
Preview site indexed and showing up in search results

### ISSUE THREAD

**Issue by nschneid** [acl-org/acl-anthology#2741] opened 2023-08-17 03:11 UTC
### Confirm that this is a bug report

- [X] I want to report an issue that does _not_ concern paper or author metadata.
- [X] I have searched for similar existing issues first.

### Problem Description

<img width="1138" alt="image" src="https://github.com/acl-org/acl-anthology/assets/985263/e534fbff-c288-4f92-9ab8-d10df63ae3f4">

The first result links to https://preview.aclanthology.org/ingestion-script-update/people/a/anuoluwapo-aremu/. I take it this is not the intended behavior?

**Comment by mbollmann** [comment] 2023-08-17 08:15
Duplicate of #2425 that was fixed in May. It seems that preview branch you see linked there was published before that and not updated since. Maybe we should force-update all older preview branches. @mjpost @anthology-assist

**Closed by mbollmann** 2023-08-17 08:15 UTC
Labels: bug
