### ISSUE TITLE
DOI doesn't fully work with NSF-PAR

### ISSUE THREAD

**Issue by jeisner** [acl-org/acl-anthology#2088] opened 2022-08-02 18:17 UTC
#### Issue description

In the U.S., work funded by the National Science Foundation has to be deposited into their repository, NSF-PAR.  The easiest way to upload a paper is to provide the DOI to the NSF-PAR system.  This works correctly for TACL DOIs.  However, for the DOIs that are managed by the ACL Anthology, it only works partially and I have to fill in the proceedings title and optionally other info.

#### Steps to reproduce the issue

1. Visit https://nsfpar.research.gov/addproduct.html with an NSF account
2. Choose "publication" and "Yes, the DOI number is available"
3. Enter 10.18653/v1/2022.acl-long.110 and submit

#### What's the expected result?

The bibliographic data for the paper should appear.
That is what you get with a TACL URL, such as 10.1162/tacl_a_00060:

- ![screenshot754](https://user-images.githubusercontent.com/2395181/182444760-30f50284-186c-4da6-b88c-68fcdcaab7b0.png)

#### What's the actual result?

A form with incomplete bibliographic data, which prompts to fill in the conference proceedings title and potentially make other changes.  

The proceedings title, month, and abstract are all missing on this form, even though they're available from the Anthology page. 

This screen does correctly show the publication's title, authors, page range, and year, although the publication date is given as January 1 of that year.

- ![screenshot753](https://user-images.githubusercontent.com/2395181/182444712-8607ac23-68f1-448c-a3e9-85da2c6adc82.png)

#### Additional details

I don't know how bib info is harvested from DOIs, but I'm guessing that the DOI is resolved to a webpage and the info is retrieved from in meta fields in the HTML.  In that case, maybe the Anthology webpage doesn't provide quite the right meta fields, whereas the TACL webpage does?

Here's a [guide to NSF-PAR](https://www.research.gov/common/attachment/Desktop/NSF-PAR_Getting_Started_Guide.pdf).

**Comment by jeisner** [comment] 2022-08-02 18:26
The error message in the screenshot says "Please contact the publisher to update the publication information," so that's what I'm trying to do by filing this issue. :smile:  It may be that someone at NSF works with publishers on this kind of thing, if you need help, but I'm not sure where to find them.

**Comment by mjpost** [comment] 2022-08-05 16:35
Thanks for the detailed report. This has been raised in the past (#1432) by @neubig and @nscheid. We have an assistant now so I'll ask her to take a look.

**Comment by jeisner** [comment] 2022-08-05 16:39
Thanks - sorry not to have found #1432 first.  (Feel free to merge)

**Comment by mjpost** [comment] 2022-08-05 16:47
No problem, you helped raise the priority.

**Comment by mjpost** [comment] 2022-08-05 16:47
Closing as duplicate of #1432.

**Closed by mjpost** 2022-08-05 16:47 UTC
Labels: bug
