### ISSUE TITLE
Auto-archive URLs

### ISSUE THREAD

**Issue by mjpost** [acl-org/acl-anthology#765] opened 2020-03-06 04:22 UTC
It would be nice to crawl *ACL papers for URLs and auto-submit them to the Internet archive (or preserve them locally).

(Inspired by [this tweet](https://twitter.com/yoavgo/status/1235671053248196626) and earlier discussions on this topic that I can't currently locate).

**Comment by mbollmann** [comment] 2020-04-26 17:35
I think this is a duplicate of #559.

**Closed by mbollmann** 2020-04-26 17:35 UTC
Labels: duplicate
